# Generated by Django 5.1.2 on 2024-10-21 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_notes_options_notes_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
